### ISSUE TITLE
Incompatible with presence validation on associated record

### ISSUE THREAD

**Issue by coreyward** [notahat/machinist#104]
It looks like the way Machinist works doesn't make it possible to do the following:

```
class Post
  has_many :comments
end

class Comment
  belongs_to :post
  validates :post_id, :presence => true
end

Comment.blueprint do
  post
end

describe Comment do
  it 'is valid when generated by Machinist' do
    Comment.make.should be_valid
  end
end
```

When I try this my test fails with the presence validation error on `Comment.post_id`.

I've temporarily worked around this by disabling this validation, but I prefer enforcing this so I have fewer orphan records lingering about.

**Comment by notahat** [comment]
This is the way ActiveRecord works. You'll get the same error if you do this:

```
post = Post.new
comment = Comment.new(:post => post)
comment.save
```

ActiveRecord isn't smart enough to save the post, and set the post_id on the comment.

If you've got a way around this, let me know!

**Comment by rgould** [comment]
Ran into this myself. The fix is to use `validates :post, presence: true` instead of using `:post_id`. This doesn't require the post object to be saved (aka have an id)

While I was at it, I added the `validates_associated :post` validation too, which causes `valid?` to be false if the associated `post.valid?` is also false.

**Comment by coreyward** [comment]
Thank you @rgould!
