### ISSUE TITLE
Add callbacks to blueprints (before_make, after_make, ... ?)

### ISSUE THREAD

**Issue by TylerRick** [notahat/machinist#23]
factory_girl has callbacks. Callbacks can be useful.

Callbacks allow a lot of flexibility for those cases where you need to do some additional setup to an object before or after Machinist does its usual thing.

Example:

<pre>
User.blueprint do
  before { |user|
    user.auto_initialize_associations = false
    [:code1, :code2].each do |attr_name|
      user.send "#{attr_name}=", '1'
    end
  }
  name
  email_address
  address
  after { |user| do_something_to(user) }
  after { |user| user.activate! }
end
</pre>

**Comment by notahat** [comment]
The blueprint is executed for each make, so it's very simple to do this in Machinist:

```
User.blueprint do
  # stuff you want to do before the make goes here
  name
  email_address
  # stuff you want to do after the make goes here
end
```

**Comment by TylerRick** [comment]
You have a pretty good point. Thanks. :)

**Comment by triskweline** [comment]
notahat, while your example is useful in some cases, it might be awkward to do something to the object being made, because the blueprint is evaluated against an object in the Machinist internals.

Also there is the use case of needing to run code after Machinist has called `save`, for instance the `has_many` caveat you are citing in the README.

We just published a gem [machinist_callbacks](http://github.com/makandra/machinist_callbacks) that adds `before_make` and `after_make` callbacks to machinist.
