### ISSUE TITLE
Has and belongs to many documentation

### ISSUE THREAD

**Issue by ened** [notahat/machinist#38]
Hi:

Supposed I have a model Location which is linked to many categories through a location_categories table:
    has_many :location_categories, :dependent => :destroy
    has_many :categories, :through => :location_categories
    validates_presence_of :categories

How could I possibly create the objects for that via Machinist. What I learned now is I need a helper method to create the plan for the Location first, then create the Categories and assign them to the plan, then create the final object. 
And if my next model is validating the presence of a Location I would need another helper method?

It seems it's not supported in Machinist by default or through some other methods due to various reasons (ActiveRecord not suitable etc etc.). So if anyone knows a solution, pls. add it here and get it included in the README.

BR,
Seb

**Comment by ened** [comment]
I had some more fun and added helper methods as recommended in : http://groups.google.com/group/machinist-users/browse_thread/thread/b6852b079e4e6663 

Device => Location => Categories
(in test_helper.rb):
    def make_device_with_location *args 
      d = Device.plan(args)
      d[:location_id]= make_location_with_categories.to_param
      Device.create!(d)
    end 

```
def make_location_with_categories *args 
  l = Location.plan(args)
  l[:category_ids]=[]
  3.times { l[:category_ids] << Category.make.to_param } 
  Location.create!(l)
end
```

While this looks easy, it still needs "plan" methods later. :-(

What's interesting as well is that this ain't work for the device-show method:
    get :show, :id => make_device_with_location.to_param
returns a nil for @device.location in the view file.

Anyone got through this?

**Comment by notahat** [comment]
This is discussion for the Google group, not the issue tracker, so I'm closing it.

Machinist discourages you from creating object through has_many or habtm relationships in blueprint because ActiveRecord implicit saves will bite you if you try. For things like habtm relationships, you need to manage the save order, so you need create the objects in the right order yourself. That usually means creating both sides of the habtm relationship first, and then linking them up, but it depends on the validations on your models.
