### ISSUE TITLE
Sham generates same value each time for some values.

### ISSUE THREAD

**Issue by grimen** [notahat/machinist#7]
I got this problem with Sham: I use Forgery for generating gender-abbreviations "M" vs. "F". This works perfectly in IRB like this:

Forgery(:personal).abbreviated_gender

but with the same using sham:

Sham.gender(:unique => false) { Forgery(:personal).abbreviated_gender }

I get "F" all the time for hundres of values.

Any clue?

**Comment by adamsalter** [comment]
This is related to the seed value that machinist sets...

Setting the random seed has several effects...

a) you can get issues like this where it seems the other library resets the seed before generating... meaning that machinist sets it back and you always get the same value from `rand`

b) If you use Faker or other library, you will always get the same values as every other person using Faker... potentially a security flaw since rand is no longer random...

My suggestions would be:
- have machinist use a rails constant (if available), so that the randomness is the same for that project, but not _every_ rails project. (I was thinking `ActionController::Base.session[:secret]`)
- have faker increment the seed every time it resets it... so the seed is (1) first time, (2) second time, not just (1) every time. Thereby fixing above behaviour.
- have an option to turn off resetting the seed, so all data from machinist is truely random.

**Comment by adamsalter** [comment]
A couple of examples:

```
Machinist.sham_seed = "abc"
Machinist.sham_seed = ActionController::Base.session[:secret]
#turn on true randomness
Machinist.sham_seed = false
```

**Comment by grimen** [comment]
OK, thanks!

**Comment by adamsalter** [comment]
Ehhh... sorry I'm not saying this is a fix to your problem. More a suggestion to notahat, or whoever is maintaining machinist.

I was having similar problems to you and although I worked around it, I would like to see the fixes I suggested above as a more permanent fix. I don't personally like knowing that all my Machinist+Faker code is generating exactly the same data as every other user. I know machinist is basically for testing and development, but still it is a kind of security flaw if an external individual knows you are using it. They can duplicate your data very easily.

In your case you might, either be able to fix it by calling `srand` in between your data generation, e.g.

```
User.blueprint do
  name { generate_name }
  srand
  email { generate_email }
end
```

or just change `srand(1)` to `srand` in the code:

http://github.com/notahat/machinist/blob/3b2a729f0bb1723f50ad2ffc819bbcd18626130e/lib/sham.rb#L73

**Comment by adamsalter** [comment]
Should probably raise a new ticket for my suggestions... ;)

**Comment by adamsalter** [comment]
New issue for my suggestions:

http://github.com/notahat/machinist/issues#issue/9

**Comment by notahat** [comment]
Back to the original issue, I'm not sure why you're seeing this problem. Got some code I can run that demonstrates it?

**Comment by notahat** [comment]
Can't reproduce.
